### ISSUE TITLE
你好，字节跳动联邦学习方向收人嘛

### ISSUE THREAD

**Issue by realTaki** [shishaochen/PbcCrawler#1]
我近期在找相关工作机会，不知道有没有机会聊一下呀！

**Comment by shishaochen** [comment]
@KAndHisC 不好意思，蛮久没登 GitHub ，错过你消息了。请问你还在寻找联邦学习的工作机会吗？可以邮件简历给我或者进一步沟通。

**Comment by realTaki** [comment]
抱歉，暂时不考虑啦，谢谢！
